version: '3.7'
networks:
  default:
      name: reboarding-network
services:

  boarding-service:
    image: boarding-service
    container_name: boarding-service
    ports:
      - 8081:8081
    expose:
      - 8081

  terminal-service:
    image: terminal-service
    container_name: terminal-service
    ports:
      - 8082:8082
    expose:
      - 8082